"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter(); const [mode, setMode] = useState<"login"|"register">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const r = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password, name: mode === "register" ? name : undefined }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Request failed"); router.push("/"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-card"><div className="brand"><div className="brand-mark">✦</div> AutoPilot Social</div><h1>{mode === "login" ? "Welcome back" : "Create your studio"}</h1><p className="muted">One workspace for automated social content.</p><form className="form" onSubmit={submit}>{mode === "register" && <div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required /></div>}<div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required /></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters" minLength={8} required /></div>{error && <div className="error">{error}</div>}<button className="btn primary" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form><button className="link-btn" onClick={()=>setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "New here? Create an account" : "Already have an account? Sign in"}</button></div></main>;
}
